export interface PerfilPostulante {
    nombres: string,
    apellido: string,
    nombreautopercibido: string,
    fecnac: string,
    nrofiscal: number,
    sexo: string,
    pais: string,
    tipoDoc: string,
    nrodoc: number,
    estadoCivil: number,
    foto: string,
    tienelicencia: boolean,
    tienehijos: boolean,
    celular: number,
    telefono: number,
    mail: string,
    numcalle: number,
    provincia: number,
    partido: number,
    localidad: number,
    calle: number,
    filesize: number,
    otroGenero: string,
    rutacv: string,
    estado: boolean
}